- name: "Join a Swarm"
  community.general.docker_swarm:
    state: join
    remote_addrs: [ "{{ hostvars['leader']['ansible_default_ipv4']['address'] }}:2377" ]
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars['token']['value'] }}"